# ============================================================
# Dependencies:
# - dataclasses
# - pathlib
# - infra_core
# ============================================================

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from infra_core import (
    CredentialsLoader,
    CredentialsSetupService,
    FernetEncryption,
    PathConfig,
    PathManager,
    RootConfig,
    RootConfigProvider,
)
from infra_core.core.path.path_config_provider import PathConfigProvider
from infra_core.core.path.path_definition import PathDefinition
from infra_core.credentials.models.base_credentials import BaseCredentials

PROJECT_ROOT: Path = Path(__file__).resolve().parent
PROFILE_NAME: str = "simple_example"
SECRETS_DIR_NAME: str = "example_runtime_secrets"


@dataclass(frozen=True)
class ExampleCredentials(BaseCredentials):
    """
    Simple credentials model used by the example.

    :example:
        >>> creds = ExampleCredentials(api_token="abc", client_id="123")
        >>> creds.api_token
        'abc'
    """

    api_token: str
    client_id: str


def configureRoot() -> None:
    """
    Configure root resolution for the current repository.

    :return: None

    :example:
        >>> configureRoot()
    """
    config = RootConfig(
        markers=(
            ".git",
            "pyproject.toml",
        ),
        start_path=PROJECT_ROOT,
    )
    RootConfigProvider.set(config)


def configurePaths() -> None:
    """
    Configure the paths used by the credentials flow.

    :return: None

    :example:
        >>> configurePaths()
    """
    config = PathConfig()

    config = config.addPath(
        "secrets_dir",
        PathDefinition(SECRETS_DIR_NAME),
    )
    config = config.addPath(
        "secret_key",
        PathDefinition(f"{SECRETS_DIR_NAME}/key.key"),
    )
    config = config.addPath(
        "credentials",
        PathDefinition(f"{SECRETS_DIR_NAME}/{{name}}.json"),
    )

    PathConfigProvider.set(config)


def cleanupExampleFiles() -> None:
    """
    Remove files generated by previous executions of the example.

    :return: None

    :example:
        >>> cleanupExampleFiles()
    """
    manager = PathManager()

    manager.deleteResource(
        "credentials",
        variables={"name": PROFILE_NAME},
        missing_ok=True,
    )
    manager.deleteResource("secret_key", missing_ok=True)
    manager.deleteResource("secrets_dir", missing_ok=True)


def runExample() -> None:
    """
    Execute a full credentials setup and load flow.

    The flow is:
    - configure root
    - configure paths
    - cleanup previous example artifacts
    - setup encrypted credentials using Fernet
    - load the credentials back from disk

    :return: None

    :raises Exception:
        When any setup or load step fails

    :example:
        >>> isinstance(runExample(), type(None))
        True
    """
    configureRoot()
    configurePaths()
    cleanupExampleFiles()

    credentials = ExampleCredentials(
        api_token="token-123",
        client_id="client-xyz",
    )

    setupService = CredentialsSetupService(FernetEncryption)
    setupService.setup(credentials, name=PROFILE_NAME)

    loadedCredentials = CredentialsLoader.load(
        ExampleCredentials,
        FernetEncryption,
        name=PROFILE_NAME,
    )

    manager = PathManager()

    print("Root:", manager.getRoot())
    print("Secret key:", manager.getPath("secret_key"))
    print(
        "Credentials file:",
        manager.getPath("credentials", variables={"name": PROFILE_NAME}),
    )
    print("Loaded api_token:", loadedCredentials.api_token)
    print("Loaded client_id:", loadedCredentials.client_id)


if __name__ == "__main__":
    runExample()
